### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf-test-harness#107]
Tests running in github actions appear to fail with `timeout` problems.

If you add some code to surface information on unhandled rejections:

```
process.on('unhandledRejection', function (reason) {
  throw reason;
});
```

You see they aren't actually timing out, they are crashing in puppeteer

```
(node:1806) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/puppeteer-core/lib/Page.js:215:24)
    at CDPSession.Page.client.on.event (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/puppeteer-core/lib/Page.js:123:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/puppeteer-core/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/home/runner/work/config-ug-vht/config-ug-vht/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

These tests seem to pass reliabily locally, but fail intermittently in github actions.

**Comment by kennsippell** [comment]
Potential fix? https://github.com/puppeteer/puppeteer/issues/1175#issuecomment-342406793

**Comment by derickl** [comment]
Disabling shared memory didn't work. I'll try increasing it. Nice find!

**Comment by eljhkrr** [comment]
I've managed to get it working by upgrading to node 12+ and chromium-resolver to 9

**Comment by kennsippell** [comment]
@eljhkrr Can you run the suite multiple times (maybe ~10-20 times) to confirm this is reliable? Do we need both those changes or is just the chromium-resolver upgrade enough?

**Comment by derickl** [comment]
The two are related - newer puppeteer releases depend on higher node releases
