### ISSUE TITLE
Improve handling of empty config projects

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-conf-test-harness#31]
Steps to reproduce:
1. Run `medic-conf initialise-project-layout`
2. Wire up a simple test using `medic-conf-test-harness`
```javascript
const { expect } = require('chai');

const Harness = require('medic-conf-test-harness');
const harness = new Harness({ verbose: true });

describe('Getting started tests', () => {
  before(async () => { return await harness.start(); });
  after(async () => { return await harness.stop(); });
  beforeEach(async () => { return await harness.clear(); });
  afterEach(() => { expect(harness.consoleErrors).to.be.empty; });

  const formName = 'baseline_hh_survey';
  it(`${formName} can be loaded`, async () => {
    await harness.loadForm(`app/${formName}`);
    expect(harness.state.pageContent).to.include(`id="${formName}"`);
  });
});
```
An exception is raised on contact summary content

```
Error: Invalid contactSummary. Object is expected
      at serializeContactSummary (node_modules/medic-conf-test-harness/src/harness.js:466:11)
      at Harness.loadForm (node_modules/medic-conf-test-harness/src/harness.js:155:38)
      at Context.<anonymous> (test/sample-test.js:14:19)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by kennsippell** [comment]
@eljhkrr I'll handle this early next week

**Comment by eljhkrr** [comment]
Thank you

**Comment by kennsippell** [comment]
I think the harness is behaving as expected here. The contact summary created by medic-conf for this operation is invalid. Should correct that as a bug in medic-conf.

https://github.com/medic/medic-conf/issues/302
